### ISSUE TITLE
run circuits on slurm and include transpiler calls

### ISSUE THREAD

**Issue by csookim** [csookim/qibo_transpiler_cskim#33]
- H / SWAP gates

**Comment by marekgluza** [comment]
```python
import qibo
#qibo.set_backend("qibolab",platform="qw5q_platinum")
c = qibo.Circuit(5)
c.add(qibo.gates.GPI2(0,0))
c.add(qibo.gates.M(0,1,2,3,4))
result = c(nshots=100)
print(result.samples())

c = qibo.Circuit(5)
c.add(qibo.gates.GPI2(0,0))


c.add(qibo.gates.GPI2(2,0))
c.add(qibo.gates.CZ(0,2))
c.add(qibo.gates.GPI2(2,0))
c.add(qibo.gates.GPI2(0,0))
c.add(qibo.gates.CZ(2,0))
c.add(qibo.gates.GPI2(0,0))
c.add(qibo.gates.GPI2(2,0))
c.add(qibo.gates.CZ(0,2))
c.add(qibo.gates.GPI2(2,0))

c.add(qibo.gates.M(0,1,2,3,4))
result = c(nshots=100)
print(result.samples())
print(result.probabilities())
```

**Comment by marekgluza** [comment]
```
sbatch -p qw5q_platinum run_hadamard.sh 
watch -n 1 squeue -u your.username
```

```
#!/bin/bash

module load qibo
echo $QIBOLAB_PLATFORMS
python h.py
```

**Comment by marekgluza** [comment]
- [ ] check that CZ(0,1) doesn't work as opposed to CZ(0,2)
- [ ] demonstrate transpiler use to run CZ(0,2)

**Comment by marekgluza** [comment]
run on `-p sim` to check and on `-p qw5q_platinum`

**Comment by marekgluza** [comment]
use `sinfo` command to check available platforms

cf. email from qrc account creation

**Comment by csookim** [comment]
## Result

I ran a circuit on iqm5 with only H and SWAP gates. The code is:

```py
from qibo import gates
from qibo.models.circuit import Circuit
from qibo.transpiler.pipeline import Passes
from qibo.transpiler.unroller import NativeGates, Unroller

circuit = Circuit(3)
circuit.add(gates.H(0))
...

ng = NativeGates.default()
custom_pipeline = Passes([Unroller(native_gates=ng)])
transpiled_circuit, _ = custom_pipeline(circuit)

print("Before unrolling:")
print(circuit.draw())
print("After unrolling:")
print(transpiled_circuit.draw())

results = transpiled_circuit(nshots=100)
results.state()
```

When I ran this, 

```py
circuit = Circuit(3)
circuit.add(gates.H(0))
circuit.add(gates.SWAP(0, 1))
```
I got the expected error

```
Before unrolling:
q0: ─H─x─
q1: ───x─
q2: ─────
After unrolling:
q0: ─Z─GPI2─o─Z─GPI2─Z─Z─GPI2─o────────
q1: ─Z─GPI2─Z─Z─GPI2─o─Z─GPI2─Z─Z─GPI2─
q2: ───────────────────────────────────

...

ValueError: Calibration for CZ gate between qubits 0 and 1 not found.
```

However, when I ran this,

```py
circuit = Circuit(3)
circuit.add(gates.H(0))
circuit.add(gates.SWAP(0, 2))
```

I got an error:

```
[Qibo 0.2.11|INFO|2024-08-13 08:40:31]: Loading platform /nfs/tools/qibolab_platforms_qrc/iqm5q
[Qibo 0.2.11|INFO|2024-08-13 08:40:31]: Using qibolab (/nfs/tools/qibolab_platforms_qrc/iqm5q) backend on /CPU:0
Before unrolling:
q0: ─H─x─
q1: ───|─
q2: ───x─
After unrolling:
q0: ─Z─GPI2─o─Z─GPI2─Z─Z─GPI2─o────────
q1: ────────|────────|────────|────────
q2: ─Z─GPI2─Z─Z─GPI2─o─Z─GPI2─Z─Z─GPI2─
Traceback (most recent call last):
  File "/nfs/users/changsoo.kim/test.py", line 20, in <module>
    results = transpiled_circuit(nshots=100)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibo/models/circuit.py", line 1113, in __call__
    return self.execute(initial_state=initial_state, nshots=nshots)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibo/models/circuit.py", line 1109, in execute
    return GlobalBackend().execute_circuit(self, initial_state, nshots)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibolab/backends.py", line 100, in execute_circuit
    sequence, measurement_map = self.compiler.compile(circuit, self.platform)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibolab/compilers/compiler.py", line 156, in compile
    gate_sequence, gate_phases = self._compile_gate(
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibolab/compilers/compiler.py", line 107, in _compile_gate
    gate_sequence, gate_phases = rule(gate, platform)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibolab/compilers/default.py", line 88, in cz_rule
    return platform.create_CZ_pulse_sequence(gate.qubits)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibolab/platform/platform.py", line 354, in create_CZ_pulse_sequence
    return self.pairs[pair].native_gates.CZ.sequence(start)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibolab/native.py", line 248, in sequence
    sequence.add(pulse.pulse(start=start))
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibolab/native.py", line 82, in pulse
    return FluxPulse(
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibolab/pulses.py", line 1180, in __init__
    super().__init__(
  File "<string>", line 13, in __init__
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibolab/pulses.py", line 790, in __post_init__
    self.shape = PulseShape.eval(self.shape)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibolab/pulses.py", line 223, in eval
    return globals()[shape_name](*shape_parameters)
TypeError: Custom.__init__() takes from 2 to 3 positional arguments but 181 were given
```

Should I create an issue about this?

**Comment by marekgluza** [comment]
Yes, in qibolab

Thanks for the update!
